import { describe, expect, it } from "vitest";
import {
  generateOpencodeHooksBridge,
  parseHooksJsonForBridge,
} from "../../../../../../src/contexts/tools/domain/profiles/opencode/opencode-hooks-bridge.js";

// Built rather than written as a literal "${CLAUDE_PLUGIN_ROOT}" string: biome reads a plain
// string holding "${...}" as a forgotten template literal.
const ROOT = "$" + "{CLAUDE_PLUGIN_ROOT}";

const THREE_EVENT_HOOKS_JSON = JSON.stringify({
  hooks: {
    SessionStart: [
      { hooks: [{ type: "command", command: `node ${ROOT}/hooks/update_memory.js` }] },
    ],
    Stop: [{ hooks: [{ type: "command", command: `node ${ROOT}/hooks/journal.cjs turn-end` }] }],
    PostToolUse: [
      {
        matcher: "Bash",
        hooks: [{ type: "command", command: `node ${ROOT}/hooks/journal.cjs tool-used` }],
      },
    ],
  },
});

describe("generateOpencodeHooksBridge", () => {
  it("generates a bridge module for a hooks.json naming all three mapped events", () => {
    const generated = generateOpencodeHooksBridge(THREE_EVENT_HOOKS_JSON, "aidd-sample");

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by aidd from plugins/aidd-sample/hooks/hooks.json - do not edit by hand.
      // OpenCode's plugin loader scans no "hooks" family and this profile writes no hooks.json
      // (build.ts's skipHooksJson, translated here rather than skipped) - this file is the only
      // trigger this plugin's declared hooks have on OpenCode. See opencode-hooks-bridge.ts for
      // the mapping this generator applies and the measurements behind it.
      import { spawn } from "node:child_process";
      import { fileURLToPath } from "node:url";

      // Never process.execPath: OpenCode ships as its own standalone binary (see
      // plugins/aidd-telemetry/hooks/opencode-plugin.js:29-30) - that path names \`opencode\`
      // itself, not a Node runtime able to run this plugin's own hook scripts.
      const HOOKS_DIR = fileURLToPath(new URL("../hooks/aidd-sample/", import.meta.url));

      const SESSION_START = [{"script":"update_memory.js","args":[]}];
      const STOP = [{"script":"journal.cjs","args":["turn-end"]}];
      const POST_TOOL_USE = [{"script":"journal.cjs","args":["tool-used"],"matcher":"Bash"}];

      // Asynchronous on purpose, unlike opencode-plugin.js's own spawnSync: that file spawns at
      // most one script per event, this one can spawn one per matching hook across every mapped
      // event, and blocking OpenCode's event loop once per hook multiplies the cost its own
      // comment already accepts for a single call. A failed spawn (ENOENT, a killed timeout)
      // must not throw past this function - both listeners below, plus the caller's own
      // try/catch, exist because a spawn that never launches can still throw on the stdin write.
      function runHook(script, args, payload, directory) {
        const child = spawn("node", [HOOKS_DIR + script, ...args], {
          cwd: directory,
          stdio: ["pipe", "ignore", "ignore"],
          timeout: 5000,
        });
        child.on("error", () => {});
        child.stdin.on("error", () => {});
        child.stdin.end(JSON.stringify(payload));
      }

      /** Pure: \`session.idle\` -> every Stop hook's own {script, args, payload} - or \`[]\` for
       * any other event. Exported as a property (never a second named export - F6) so this
       * generated module's own mapping can be asserted without spawning anything, the same seam
       * \`AiddTelemetry.journalCallFor\` already gives opencode-plugin.js. */
      function stopCallsFor(event, directory) {
        if (event?.type !== "session.idle") return [];
        const sessionId = event.properties?.sessionID;
        return STOP.map((hook) => ({
          script: hook.script,
          args: hook.args,
          payload: { hook_event_name: "Stop", session_id: sessionId ?? null, cwd: directory },
        }));
      }

      /** Pure: \`message.part.updated\` for a completed tool part -> every PostToolUse hook whose
       * matcher (absent, or an exact / pipe-separated tool name) allows this tool - or \`[]\` for
       * any other event, an incomplete part, or one naming no tool. */
      function postToolUseCallsFor(event, directory) {
        if (event?.type !== "message.part.updated") return [];
        const part = event.properties?.part;
        if (part?.type !== "tool" || part.state?.status !== "completed") return [];
        const toolName = part.tool;
        const sessionId = event.properties?.sessionID;
        const matches = (matcher) => !matcher || matcher.split("|").includes(toolName);
        return POST_TOOL_USE.filter((hook) => matches(hook.matcher)).map((hook) => ({
          script: hook.script,
          args: hook.args,
          payload: {
            hook_event_name: "PostToolUse",
            session_id: sessionId ?? null,
            cwd: directory,
            tool_name: toolName,
            tool_input: part.state.input,
          },
        }));
      }

      export const AiddSampleHooks = async (input) => {
        // SessionStart's own approximation (module doc comment above): fired once here, never
        // per session. Silent on purpose, the same rule journal.cjs's own main() and
        // opencode-plugin.js's own event handler both state: a measurement or a memory refresh
        // that breaks OpenCode's own startup is worse than one that never ran.
        try {
          for (const hook of SESSION_START) {
            runHook(
              hook.script,
              hook.args,
              { hook_event_name: "SessionStart", session_id: null, cwd: input.directory },
              input.directory
            );
          }
        } catch {
          // Silent on purpose - see above.
        }
        return {
          event: async ({ event }) => {
            try {
              const calls = [
                ...stopCallsFor(event, input.directory),
                ...postToolUseCallsFor(event, input.directory),
              ];
              for (const call of calls) {
                runHook(call.script, call.args, call.payload, input.directory);
              }
            } catch {
              // Silent on purpose - see above.
            }
          },
        };
      };

      AiddSampleHooks.stopCallsFor = stopCallsFor;
      AiddSampleHooks.postToolUseCallsFor = postToolUseCallsFor;
      "
    `);
  });

  it("returns null for a hooks.json naming only an unmapped event", () => {
    const hooksJson = JSON.stringify({
      hooks: { PreToolUse: [{ hooks: [{ type: "command", command: `${ROOT}/hooks/check.sh` }] }] },
    });

    expect(generateOpencodeHooksBridge(hooksJson, "aidd-test")).toBeNull();
  });

  it("returns null for a hooks.json with no hooks at all", () => {
    expect(generateOpencodeHooksBridge(JSON.stringify({ hooks: {} }), "aidd-test")).toBeNull();
  });

  it("generates a bridge for a plugin whose hooks name only Stop", () => {
    const hooksJson = JSON.stringify({
      hooks: {
        Stop: [
          { hooks: [{ type: "command", command: `node ${ROOT}/hooks/journal.cjs turn-end` }] },
        ],
      },
    });

    expect(generateOpencodeHooksBridge(hooksJson, "aidd-test")).toContain(
      'const SESSION_START = [];\nconst STOP = [{"script":"journal.cjs","args":["turn-end"]}];\nconst POST_TOOL_USE = [];\n'
    );
  });

  it("generates a bridge for a plugin whose hooks name only PostToolUse", () => {
    const hooksJson = JSON.stringify({
      hooks: {
        PostToolUse: [
          { hooks: [{ type: "command", command: `node ${ROOT}/hooks/journal.cjs tool-used` }] },
        ],
      },
    });

    expect(generateOpencodeHooksBridge(hooksJson, "aidd-test")).toContain(
      'const SESSION_START = [];\nconst STOP = [];\nconst POST_TOOL_USE = [{"script":"journal.cjs","args":["tool-used"]}];\n'
    );
  });

  it("names the bridge's export after the plugin even when its name holds an empty segment", () => {
    expect(generateOpencodeHooksBridge(THREE_EVENT_HOOKS_JSON, "aidd--sample")).toContain(
      "export const AiddSampleHooks = async (input) => {"
    );
  });

  it("drops a hook whose command does not invoke node against its own hooks/ script", () => {
    const hooksJson = JSON.stringify({
      hooks: { Stop: [{ hooks: [{ type: "command", command: `${ROOT}/hooks/check.sh` }] }] },
    });

    expect(generateOpencodeHooksBridge(hooksJson, "aidd-test")).toBeNull();
  });
});

describe("parseHooksJsonForBridge", () => {
  const stopCallsOf = (command: string) =>
    parseHooksJsonForBridge(
      JSON.stringify({ hooks: { Stop: [{ hooks: [{ type: "command", command }] }] } })
    ).stop;

  it("splits a hook's arguments on any run of whitespace", () => {
    expect(stopCallsOf(`node ${ROOT}/hooks/journal.cjs turn-end   --quiet`)).toStrictEqual([
      { script: "journal.cjs", args: ["turn-end", "--quiet"] },
    ]);
  });

  it("reads a command written with surrounding whitespace", () => {
    expect(stopCallsOf(`  node ${ROOT}/hooks/journal.cjs  `)).toStrictEqual([
      { script: "journal.cjs", args: [] },
    ]);
  });

  it("skips a hook that carries no command, keeping the ones beside it", () => {
    const hooksJson = JSON.stringify({
      hooks: {
        Stop: [
          {
            hooks: [
              { type: "prompt" },
              { type: "command", command: `node ${ROOT}/hooks/journal.cjs` },
            ],
          },
        ],
      },
    });

    expect(parseHooksJsonForBridge(hooksJson).stop).toStrictEqual([
      { script: "journal.cjs", args: [] },
    ]);
  });
});
