module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    // scope-enum sits at level 1: an unlisted scope warns, it never blocks the commit.
    "scope-case": [2, "always", "kebab-case"],
    "scope-enum": [
      1,
      "always",
      [
        "aidd-context",
        "aidd-dev",
        "aidd-vcs",
        "aidd-pm",
        "aidd-refine",
        "aidd-orchestrator",
        "aidd-ui",
        "context",
        "dev",
        "vcs",
        "pm",
        "refine",
        "orchestrator",
        "ui",
        "aidd-telemetry",
        "telemetry",
        "cli",
        "kanban",
        "framework",
        "marketplace",
        "release-please",
        "release",
        "ci",
        "deps",
        "deps-dev",
        "lefthook",
        "commitlint",
        "contributing",
        "docs",
        "readme",
        "security",
        "test",
      ],
    ],
    "body-max-line-length": [0, "always"],
    "footer-max-line-length": [0, "always"],
  },
};
