from pathlib import Path
import hashlib,json,stat
base=Path('/tmp/aidd-914-p3-generation'); cases=json.loads(Path('/tmp/aidd-p3-cases.json').read_text())
def snapshot(root):
 out={}
 for p in sorted(root.rglob('*')):
  s=p.lstat();item={'mode':stat.S_IMODE(s.st_mode),'mtimeNs':s.st_mtime_ns,'type':'dir' if p.is_dir() else 'file'}
  if p.is_symlink():item={'type':'symlink','target':str(p.readlink())}
  elif p.is_file():item['sha256']=hashlib.sha256(p.read_bytes()).hexdigest()
  out[str(p.relative_to(root))]=item
 return out
before=snapshot(base)
# Modify input: clarify the verify action only; all targets already confirmed.
# Read existing trees first, check all destinations and retained resources.
for case in cases:
 root=base/case['project']/case['target']/'verify-payload'
 for p in root.rglob('*'):
  assert not p.is_symlink()
  if p.is_file():p.read_bytes()
 assert (root/'actions/01-verify.md').stat().st_mode & 0o222
for case in cases:
 p=base/case['project']/case['target']/'verify-payload/actions/01-verify.md'
 content=p.read_text().replace('Read [payload.txt](../assets/payload.txt).','Read [payload.txt](../assets/payload.txt) for this request; do not guess its content.')
 if p.read_text()!=content:p.write_text(content)
after=snapshot(base)
changes=[p for p in before if before[p]!=after[p]]
assert len(changes)==7 and all(p.endswith('actions/01-verify.md') for p in changes)
# Repeat identical modify request: interpret action in caller, reuse existing bytes.
for case in cases:
 p=base/case['project']/case['target']/'verify-payload/actions/01-verify.md'
 current=p.read_text();desired=current # Requested clarification is already present.
 assert 'do not guess its content.' in current
 if desired!=current:p.write_text(desired)
rerun=snapshot(base);assert after==rerun
out=Path('aidd_docs/tasks/2026_10/2026_10_10_kilo-native-generation-914/evidence/phase-3')
(out/'caller-modify-rerun.json').write_text(json.dumps({'before':before,'afterModify':after,'afterRerun':rerun,'changed':changes,'rerunIdentical':after==rerun},indent=2)+'\n')
# Archive real caller output trees as fixture corpus, preserving target layout.
import shutil
fixtures=Path('scripts/__tests__/fixtures/context-generation/skills');fixtures.mkdir(exist_ok=True)
for case in cases:shutil.copytree(base/case['project'],fixtures/case['project'])
shutil.copy('/tmp/aidd-p3-cases.json',fixtures/'cases.json')
p=out/'caller-receipt.json';receipt=json.loads(p.read_text());receipt['steps_completed']+=['write action and templates read, all targets preflighted together','seven explicit fixture trees generated by native caller','validate action read, host fields checked','modify plan limited to verify action, user action/assets retained','identical modify repeated, full tree bytes and mtime unchanged','actual generated outputs archived without renderer replay'];receipt['validation']=[{'file':str(p.relative_to(base)),'checks':'frontmatter and in-tree links for router; Input/Output/Process/Test for generated action; payload data exact; retained user files unchanged','findings':[]} for p in base.rglob('*') if p.is_file() and '/verify-payload/' in str(p)];p.write_text(json.dumps(receipt,indent=2)+'\n')
