from pathlib import Path
import json, hashlib
base=Path('/tmp/aidd-914-p3-generation');base.mkdir(exist_ok=True)
cases=[('native','.kilo/skills',['name','description','license','compatibility','metadata'],['.agents/skills'],{'kilo.json':'{}\n'}),('portable','.agents/skills',['name','description'],['.kilo/skills'],{'kilo.json':'{}\n','.codex/config.toml':'# fixture\n'}),('legacy','.kilo/skills',['name','description'],['.agents/skills','.kilocode/skills'],{'.kilocode/legacy.txt':'LEGACY_KEEP\n'}),('claude','.claude/skills',['name','description','allowed-tools','disable-model-invocation'],['.kilo/skills','.agents/skills'],{'CLAUDE.md':'# fixture\n'}),('codex','.agents/skills',['name','description'],['.kilo/skills'],{'.codex/config.toml':'# fixture\n'}),('opencode','.opencode/skills',['description','permission'],['.kilo/skills','.agents/skills'],{'.opencode/opencode.json':'{}\n'}),('mixed','.agents/skills',['name','description'],['.kilo/skills'],{'kilo.json':'{}\n','.codex/config.toml':'# fixture\n'})]
for project,target,fields,absent,inputs in cases:
 d=base/project;d.mkdir(exist_ok=True)
 for file,content in inputs.items():
  p=d/file;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content)
Path('/tmp/aidd-p3-cases.json').write_text(json.dumps([dict(project=p,target=t,fields=f,absent=a) for p,t,f,a,_ in cases],indent=2)+'\n')
# Scope and plan are caller decisions for authorized synthetic fixture scenarios,
# not claims that a human supplied a new interactive answer in this session.
receipt={'caller':'native Codex session','router':'aidd-context:04-skill-generate installed 2.8.1','candidate':'workspace 04-skill-generate actions/references','test_input_authority':'approved phase-3 tasks and test-strategy; synthetic choices supplied by caller','scope':{'subject':'bundled payload verification','purpose':'Read a fixture payload and produce its verification code.','name':'verify-payload','flow':'request -> verify -> answer','mode':'auto','targets':json.loads(Path('/tmp/aidd-p3-cases.json').read_text()),'choices':{'native':'Kilo native explicitly selected','portable':'portable explicitly selected','legacy':'Kilo native selected despite legacy detection','mixed':'Kilo portable and Codex explicitly selected, one shared destination','claude':'Claude fields allowed-tools Read and disable-model-invocation true requested','opencode':'permission map read allow requested'}},'plan':[{'slug':'verify','input':'verification request','output':'PAYLOAD_APPLIED:<payload>','test':'payload read traced and exact reply','dependency':'assets/payload.txt'}],'steps_completed':['installed router read','scope action read, candidate scope and detection/placement read','no existing target/name overlaps in positive fixtures','plan action read and one-action test framed'],'sources':{}}
for p in Path('plugins/aidd-context/skills/04-skill-generate').rglob('*.md'):receipt['sources'][str(p)]=hashlib.sha256(p.read_bytes()).hexdigest()
Path('aidd_docs/tasks/2026_10/2026_10_10_kilo-native-generation-914/evidence/phase-3/caller-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
