import { describe, expect, it } from "vitest";
import { generateCatalogContent } from "../../../src/domain/models/catalog.js";
import { FileHash } from "../../../src/domain/models/file-hash.js";
import { GeneratedFile } from "../../../src/domain/models/generated-file.js";
import { Manifest } from "../../../src/domain/models/manifest.js";

const FAKE_HASH = "a".repeat(32);

function makeFile(relativePath: string): GeneratedFile {
  return new GeneratedFile({ relativePath, content: "", hash: new FileHash(FAKE_HASH) });
}

function makeManifest(docsDir = "aidd_docs"): Manifest {
  return Manifest.create(docsDir);
}

describe("generateCatalogContent", () => {
  it("returns header + 'No content installed.' for empty manifest", () => {
    const manifest = makeManifest();
    const result = generateCatalogContent(manifest, "aidd_docs");

    expect(result).toContain("# AIDD Framework Catalog");
    expect(result).toContain("Generated by `aidd`");
    expect(result).toContain("No content installed.");
    expect(result).not.toContain("##");
  });

  it("generates Claude section with correct relative links from docsDir", () => {
    const manifest = makeManifest();
    manifest.addTool("claude", "1.0.0", [
      makeFile(".claude/agents/alexia.md"),
      makeFile(".claude/commands/aidd/04/implement.md"),
    ]);

    const result = generateCatalogContent(manifest, "aidd_docs");

    expect(result).toContain("## Claude");
    expect(result).toContain("[alexia.md](../.claude/agents/alexia.md)");
    expect(result).toContain("[implement.md](../.claude/commands/aidd/04/implement.md)");
    expect(result).not.toContain("No content installed.");
  });

  it("generates Docs section with links relative to docsDir", () => {
    const manifest = makeManifest();
    manifest.addDocs("1.0.0", [
      makeFile("aidd_docs/CONTRIBUTING.md"),
      makeFile("aidd_docs/memory/architecture.md"),
    ]);

    const result = generateCatalogContent(manifest, "aidd_docs");

    expect(result).toContain("## Docs");
    expect(result).toContain("[CONTRIBUTING.md](CONTRIBUTING.md)");
    expect(result).toContain("[architecture.md](memory/architecture.md)");
  });

  it("emits sections in VALID_TOOL_IDS order: claude, cursor, copilot", () => {
    const manifest = makeManifest();
    manifest.addTool("copilot", "1.0.0", [makeFile(".github/agents/foo.agent.md")]);
    manifest.addTool("claude", "1.0.0", [makeFile(".claude/agents/bar.md")]);

    const result = generateCatalogContent(manifest, "aidd_docs");

    const claudeIdx = result.indexOf("## Claude");
    const copilotIdx = result.indexOf("## Copilot");

    expect(claudeIdx).toBeGreaterThan(-1);
    expect(copilotIdx).toBeGreaterThan(-1);
    expect(claudeIdx).toBeLessThan(copilotIdx);
  });

  it("generates copilot section with correct relative links", () => {
    const manifest = makeManifest();
    manifest.addTool("copilot", "1.0.0", [makeFile(".github/agents/foo.agent.md")]);

    const result = generateCatalogContent(manifest, "aidd_docs");

    expect(result).toContain("## Copilot");
    expect(result).toContain("[foo.agent.md](../.github/agents/foo.agent.md)");
  });

  it("computes correct path.relative for custom docsDir", () => {
    const manifest = makeManifest("my_docs");
    manifest.addTool("claude", "1.0.0", [makeFile(".claude/agents/alexia.md")]);

    const result = generateCatalogContent(manifest, "my_docs");

    expect(result).toContain("[alexia.md](../.claude/agents/alexia.md)");
  });

  it("includes both tool sections and docs section together", () => {
    const manifest = makeManifest();
    manifest.addTool("claude", "1.0.0", [makeFile(".claude/agents/alexia.md")]);
    manifest.addDocs("1.0.0", [makeFile("aidd_docs/CONTRIBUTING.md")]);

    const result = generateCatalogContent(manifest, "aidd_docs");

    expect(result).toContain("## Claude");
    expect(result).toContain("## Docs");
    expect(result).not.toContain("No content installed.");
  });

  it("does not include section for tools with no files", () => {
    const manifest = makeManifest();
    manifest.addTool("claude", "1.0.0", [makeFile(".claude/agents/alexia.md")]);
    // cursor not added — should not appear

    const result = generateCatalogContent(manifest, "aidd_docs");

    expect(result).not.toContain("## Cursor");
    expect(result).not.toContain("## Copilot");
  });
});
