import { relative } from "node:path";
import type { Manifest } from "./manifest.js";
import { VALID_TOOL_IDS } from "./tool-config.js";

const HEADER =
  "# AIDD Framework Catalog\n\n> Generated by `aidd`. Do not edit manually.\n\nThis catalog lists all files installed by the AIDD framework, organized by tool. Use this as a reference for what content is present in your repository and where to find it.\n\n---\n";

export function generateCatalogContent(manifest: Manifest, docsDir: string): string {
  const sections: string[] = [];

  for (const toolId of VALID_TOOL_IDS) {
    const files = manifest.getToolFiles(toolId);
    if (files.length === 0) continue;
    const title = toolId.charAt(0).toUpperCase() + toolId.slice(1);
    sections.push(
      buildSection(
        title,
        files.map((f) => f.relativePath),
        docsDir
      )
    );
  }

  const docsFiles = manifest.getDocsFiles();
  if (docsFiles.length > 0) {
    sections.push(
      buildSection(
        "Docs",
        docsFiles.map((f) => f.relativePath),
        docsDir
      )
    );
  }

  if (sections.length === 0) {
    return `${HEADER}\nNo content installed.`;
  }

  return `${HEADER}\n${sections.join("\n")}`;
}

function buildSection(title: string, relativePaths: readonly string[], docsDir: string): string {
  const rows = relativePaths
    .map((relativePath) => {
      const link = relative(docsDir, relativePath);
      const label = relativePath.split("/").at(-1) ?? relativePath;
      return `| [${label}](${link}) |`;
    })
    .join("\n");

  return `## ${title}\n\n| File |\n|------|\n${rows}\n`;
}
