/**
 * Kilo loads JavaScript modules from `.kilo/plugin/` and requires a default descriptor with
 * `{ id, server }`. Declarative hooks.json has no Kilo runtime, so this generator turns its
 * replayable commands into that native module. Kilo 7.7.5 delivers session.created,
 * completed tool parts and session.idle through its event hook.
 */

interface ClaudeHookItem {
  readonly command?: string;
}

interface ClaudeMatcherGroup {
  readonly matcher?: string;
  readonly hooks?: readonly ClaudeHookItem[];
}

interface ClaudeHooksShape {
  readonly hooks?: Record<string, readonly ClaudeMatcherGroup[]>;
}

interface ParsedHookCall {
  readonly script: string;
  readonly args: readonly string[];
  readonly matcher?: string;
}

const COMMAND_PATTERN = /^node\s+\$\{CLAUDE_PLUGIN_ROOT\}\/hooks\/(\S+)(.*)$/;

function parseCommand(command: string | undefined): ParsedHookCall | null {
  if (typeof command !== "string") return null;
  const match = COMMAND_PATTERN.exec(command.trim());
  if (match === null) return null;
  const [, script, rest] = match;
  return { script, args: rest.trim().length === 0 ? [] : rest.trim().split(/\s+/) };
}

function parseGroups(groups: readonly ClaudeMatcherGroup[] = []): readonly ParsedHookCall[] {
  return groups.flatMap((group) =>
    (group.hooks ?? []).flatMap((hook) => {
      const parsedHook = parseCommand(hook.command);
      return parsedHook === null
        ? []
        : [group.matcher ? { ...parsedHook, matcher: group.matcher } : parsedHook];
    })
  );
}

function toIdentifier(plugin: string): string {
  return `${plugin
    .split("-")
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("")}KiloHooks`;
}

/** Generates Kilo's default descriptor; failed hooks report without blocking its session. */
export function generateKiloHooksBridge(rawHooksJson: string, plugin: string): string | null {
  const hooks = (JSON.parse(rawHooksJson) as ClaudeHooksShape).hooks;
  const sessionStart = parseGroups(hooks?.SessionStart);
  const stop = parseGroups(hooks?.Stop);
  const postToolUse = parseGroups(hooks?.PostToolUse);
  if (sessionStart.length + stop.length + postToolUse.length === 0) return null;
  const identifier = toIdentifier(plugin);
  return `// Generated by aidd: ${plugin}/hooks/hooks.json.
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const HOOKS_DIR = fileURLToPath(new URL("../hooks/${plugin}/", import.meta.url));
const SESSION_START = ${JSON.stringify(sessionStart)};
const STOP = ${JSON.stringify(stop)};
const POST_TOOL_USE = ${JSON.stringify(postToolUse)};

function runHook(script, args, payload, directory) {
  const body = JSON.stringify(payload);
  const child = spawn("node", [HOOKS_DIR + script, ...args], {
    cwd: directory,
    stdio: ["pipe", "ignore", "ignore"],
    timeout: 5000,
  });
  let reported = false;
  const report = (error) => {
    if (reported) return;
    reported = true;
    reportHookFailure(script, error);
  };
  child.on("error", report);
  child.on("close", (code, signal) => {
    if (code !== 0 || signal !== null) {
      report("exited with code " + String(code) + (signal === null ? "" : " (" + signal + ")"));
    }
  });
  child.stdin.on("error", report);
  child.stdin.end(body);
}

function reportHookFailure(script, error) {
  console.warn("[aidd] Kilo hook " + script + " failed: " + String(error));
}

function sessionStartCallsFor(event, directory) {
  if (event?.type !== "session.created") return [];
  return SESSION_START.map((hook) => ({
    script: hook.script,
    args: hook.args,
    payload: { hook_event_name: "SessionStart", session_id: event.properties?.sessionID ?? null, cwd: event.properties?.info?.directory ?? directory },
  }));
}

const ${identifier} = async ({ directory }) => {
  const sessions = new Map();
  return {
  event: async ({ event }) => {
    try {
      const properties = event?.properties;
      const id = properties?.sessionID;
      if (typeof id !== "string") return;
      if (event?.type === "session.deleted") { sessions.delete(id); return; }
      if (!sessions.has(id)) sessions.set(id, { started: false, idle: false, tools: new Set(), directory });
      const session = sessions.get(id);
      let calls = [];
      if (event?.type === "session.created" && !session.started) {
        session.started = true;
        session.directory = properties?.info?.directory ?? directory;
        calls = sessionStartCallsFor(event, session.directory);
      } else if (event?.type === "session.status" && properties?.status?.type === "busy") {
        session.idle = false;
      } else if (event?.type === "session.idle" && !session.idle) {
        session.idle = true;
        calls = STOP.map(hook => ({ ...hook, payload: { hook_event_name: "Stop", session_id: id, cwd: session.directory } }));
      } else if (event?.type === "message.part.updated") {
        const part = properties?.part;
        if (part?.type !== "tool" || part.state?.status !== "completed" || !part.tool || !part.id || session.tools.has(part.id)) return;
        session.tools.add(part.id);
        calls = POST_TOOL_USE.filter(hook => !hook.matcher || hook.matcher.split("|").includes(part.tool)).map(hook => ({ ...hook, payload: { hook_event_name: "PostToolUse", session_id: id, cwd: session.directory, tool_name: part.tool, tool_input: part.state.input } }));
      }
      for (const call of calls) {
        runHook(call.script, call.args, call.payload, call.payload.cwd);
      }
    } catch (error) {
      console.warn("[aidd] Kilo hook dispatch failed: " + String(error));
    }
  },
  };
};

${identifier}.sessionStartCallsFor = sessionStartCallsFor;

export default { id: "${plugin}-hooks", server: ${identifier} };
`;
}
