/**
 * Canonical paths used throughout the installation flow.
 * Pure data module that may be imported by any layer.
 */
export const PATHS = {
	CLAUDE_COMMANDS: ".claude/commands",
	CLAUDE_COMMANDS_IDE: ".claude/commands/ide",
	CLAUDE_COMMANDS_FLOWS: ".claude/commands/flows",
	CLAUDE_COMMANDS_CUSTOM: ".claude/commands/custom",
	CLAUDE_AGENTS: ".claude/agents",
	CLAUDE_SETTINGS: ".claude/settings.json",
	CLAUDE_MCP: ".claude/mcp.json",
	CURSOR_RULES: ".cursor/rules",
	CURSOR_COMMANDS: ".cursor/commands",
	CURSOR_COMMANDS_IDE: ".cursor/commands/ide",
	CURSOR_COMMANDS_FLOWS: ".cursor/commands/flows",
	CURSOR_COMMANDS_CUSTOM: ".cursor/commands/prompts",
	WINDSURF_RULES: ".windsurf/rules",
	WINDSURF_GLOBAL_RULES: ".windsurf/global_rules.md",
	GITHUB_DIR: ".github",
	GITHUB_AGENTS_DIR: ".github/agents",
	GITHUB_PROMPTS_DIR: ".github/prompts",
	GITHUB_INSTRUCTIONS_DIR: ".github/instructions",
	GITHUB_COPILOT_INSTRUCTIONS: ".github/copilot-instructions.md",
	GITHUB_PR_INSTRUCTIONS: ".github/pull_request_template.md",
	GITHUB_ISSUE_TEMPLATE_DIR: ".github/ISSUE_TEMPLATE",
	GITHUB_ISSUE_TEMPLATE_BUG: ".github/ISSUE_TEMPLATE/bug_report.md",
	GITHUB_ISSUE_TEMPLATE_FEATURE: ".github/ISSUE_TEMPLATE/feature_request.md",
	DOCS_TEMPLATES_DIR: "docs/templates",
	DOCS_TEMPLATES_VCS_DIR: "docs/templates/vcs",
	DOCS_TEMPLATE_PULL_REQUEST: "docs/templates/vcs/pull_request.md",
	DOCS_TEMPLATE_ISSUE: "docs/templates/vcs/issue.md",
	DOCS_TEMPLATE_RELEASE: "docs/templates/vcs/release.md",
	RULES_ENTRYPOINT: "docs/rules.md",
	CLAUDE_MD: "CLAUDE.md",
	AGENTS_MD: "AGENTS.md",
	VSCODE_DIR: ".vscode",
	VSCODE_SETTINGS: ".vscode/settings.json",
	VSCODE_EXTENSIONS: ".vscode/extensions.json",
	VSCODE_KEYBINDINGS: ".vscode/keybindings.json",
	AIDD_GLOBAL_DIR: ".aidd",
	AIDD_ROOT: "aidd",
	AIDD_ROOT_TEMPLATES: "aidd/.aidd/templates",
	PROJECT_DOCS_DIR: "docs",
	WORKTREES_DIR: "worktrees",
	ASSETS_DIR: "./assets",
} as const;

export const DOCS_DIRECTORIES = [
	"agents",
	"flows",
	"logs",
	"memory-bank",
	"prompts",
	"rules",
	"tasks",
	"templates",
	"templates/vcs",
] as const;
