import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { InitUseCase } from "../../../src/application/use-cases/init-use-case.js";
import {
  buildDeps,
  cleanupTempProject,
  createTempProject,
  FIXTURE_DIR,
  linuxPlatform,
} from "./helpers.js";

describe("init", () => {
  let tempDir: string;
  let projectRoot: string;

  beforeEach(async () => {
    ({ tempDir, projectRoot } = await createTempProject());
  });

  afterEach(async () => {
    await cleanupTempProject(tempDir);
  });

  function buildUseCase() {
    const { fs, manifestRepo } = buildDeps(projectRoot);
    return new InitUseCase(fs, manifestRepo);
  }

  it("creates an empty docs directory and a v5 manifest", async () => {
    const result = await buildUseCase().execute({ docsDir: "aidd_docs", projectRoot });

    expect(result.docsDir).toBe("aidd_docs");
    expect(existsSync(join(projectRoot, "aidd_docs"))).toBe(true);

    const raw = await readFile(join(projectRoot, ".aidd", "manifest.json"), "utf-8");
    const data = JSON.parse(raw) as Record<string, unknown>;
    expect(data.version).toBe(5);
    expect("docs" in data).toBe(false);
    expect(data.tools).toEqual({});
  });

  it("does not copy any framework docs files into the project", async () => {
    await buildUseCase().execute({ docsDir: "aidd_docs", projectRoot });

    // Only CATALOG.md is generated by CatalogUseCase post-init.
    const docsContents = await readdir(join(projectRoot, "aidd_docs"));
    expect(docsContents).toEqual(["CATALOG.md"]);
  });

  it("does not overwrite a pre-existing user file in the docs dir", async () => {
    const docFile = join(projectRoot, "aidd_docs", "README.md");
    await mkdir(join(projectRoot, "aidd_docs"), { recursive: true });
    await writeFile(docFile, "custom content");

    await buildUseCase().execute({ docsDir: "aidd_docs", projectRoot });

    expect(await readFile(docFile, "utf-8")).toBe("custom content");
  });

  it("remembers a custom docs dir name", async () => {
    await buildUseCase().execute({ docsDir: "my_docs", projectRoot });

    expect(existsSync(join(projectRoot, "my_docs"))).toBe(true);
    const raw = await readFile(join(projectRoot, ".aidd", "manifest.json"), "utf-8");
    const data = JSON.parse(raw) as Record<string, unknown>;
    expect(data.docsDir).toBe("my_docs");
  });

  it("generates CATALOG.md without tracking it in the manifest", async () => {
    await buildUseCase().execute({ docsDir: "aidd_docs", projectRoot });

    const catalogPath = join(projectRoot, "aidd_docs", "CATALOG.md");
    expect(existsSync(catalogPath)).toBe(true);
    const content = await readFile(catalogPath, "utf-8");
    expect(content).toContain("# AIDD Framework Catalog");

    const raw = await readFile(join(projectRoot, ".aidd", "manifest.json"), "utf-8");
    expect(raw).not.toContain("CATALOG.md");
  });

  describe("checkPreconditions", () => {
    it("passes when directory is truly empty", async () => {
      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot })
      ).resolves.toBeUndefined();
    });

    it("passes when only .aidd/cache/ exists (created by resolver before init runs)", async () => {
      await mkdir(join(projectRoot, ".aidd", "cache"), { recursive: true });
      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot })
      ).resolves.toBeUndefined();
    });

    it("passes when docs directory already exists without tool signals", async () => {
      await mkdir(join(projectRoot, "aidd_docs"), { recursive: true });
      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot })
      ).resolves.toBeUndefined();
    });

    it("aborts with adopt guidance when .claude/ contains AIDD frontmatter", async () => {
      const commandDir = join(projectRoot, ".claude", "commands", "aidd", "02");
      await mkdir(commandDir, { recursive: true });
      await writeFile(
        join(commandDir, "brainstorm.md"),
        "---\nname: aidd:02:brainstorm\ndescription: test\n---\nbody"
      );

      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot })
      ).rejects.toThrow("Repository:");
    });

    it("aborts with adopt guidance when .opencode/ contains AIDD frontmatter", async () => {
      const commandDir = join(projectRoot, ".opencode", "commands", "aidd", "02");
      await mkdir(commandDir, { recursive: true });
      await writeFile(
        join(commandDir, "brainstorm.md"),
        "---\nname: aidd:02:brainstorm\ndescription: test\n---\nbody"
      );

      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot })
      ).rejects.toThrow("AIDD files detected but no manifest found");
    });

    it("passes when .claude/ exists without AIDD frontmatter", async () => {
      const commandDir = join(projectRoot, ".claude", "commands");
      await mkdir(commandDir, { recursive: true });
      await writeFile(
        join(commandDir, "my-command.md"),
        "---\nname: my-command\ndescription: custom\n---\nbody"
      );

      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot })
      ).resolves.toBeUndefined();
    });

    it("aborts when already initialized without --force", async () => {
      await buildUseCase().execute({ docsDir: "aidd_docs", projectRoot });
      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot })
      ).rejects.toThrow(/Already initialized \(docs in "aidd_docs"\)/);
    });

    it("--force: fails with guidance when no manifest exists", async () => {
      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot, force: true })
      ).rejects.toThrow("No AIDD manifest found");
    });

    it("--force: passes when manifest exists", async () => {
      await buildUseCase().execute({ docsDir: "aidd_docs", projectRoot });
      await expect(
        buildUseCase().checkPreconditions({ docsDir: "aidd_docs", projectRoot, force: true })
      ).resolves.toBeUndefined();
    });
  });

  describe("--force", () => {
    it("uses existing docsDir when --force without explicit --docs-dir", async () => {
      await buildUseCase().execute({ docsDir: "my_docs", projectRoot });
      const result = await buildUseCase().execute({
        docsDir: "aidd_docs",
        projectRoot,
        force: true,
      });
      expect(result.docsDir).toBe("my_docs");
      const raw = await readFile(join(projectRoot, ".aidd", "manifest.json"), "utf-8");
      const data = JSON.parse(raw) as Record<string, unknown>;
      expect(data.docsDir).toBe("my_docs");
    });

    it("moves docs to new dir when --force with explicit --docs-dir", async () => {
      await buildUseCase().execute({ docsDir: "aidd_docs", projectRoot });
      const result = await buildUseCase().execute({
        docsDir: "docs",
        explicitDocsDir: "docs",
        projectRoot,
        force: true,
      });
      expect(result.docsDir).toBe("docs");
      const raw = await readFile(join(projectRoot, ".aidd", "manifest.json"), "utf-8");
      const data = JSON.parse(raw) as Record<string, unknown>;
      expect(data.docsDir).toBe("docs");
      expect(existsSync(join(projectRoot, "docs"))).toBe(true);
    });

    it("does not touch tool distributions", async () => {
      const { fs, manifestRepo, loader, hasher, logger } = buildDeps(projectRoot);
      const initUseCase = new InitUseCase(fs, manifestRepo);
      await initUseCase.execute({ docsDir: "aidd_docs", projectRoot });

      const { InstallUseCase } = await import(
        "../../../src/application/use-cases/install/install-use-case.js"
      );
      const installUseCase = new InstallUseCase(
        fs,
        manifestRepo,
        loader,
        hasher,
        logger,
        linuxPlatform
      );
      await installUseCase.execute({
        toolIds: ["claude" as import("../../../src/domain/tools/registry.js").ToolId],
        frameworkPath: FIXTURE_DIR,
        version: "test",
        docsDir: "aidd_docs",
        projectRoot,
      });
      const rawBefore = await readFile(join(projectRoot, ".aidd", "manifest.json"), "utf-8");
      const toolsBefore = (JSON.parse(rawBefore) as { tools: Record<string, unknown> }).tools;

      await initUseCase.execute({ docsDir: "aidd_docs", projectRoot, force: true });

      const rawAfter = await readFile(join(projectRoot, ".aidd", "manifest.json"), "utf-8");
      const toolsAfter = (JSON.parse(rawAfter) as { tools: Record<string, unknown> }).tools;
      expect(JSON.stringify(toolsAfter)).toBe(JSON.stringify(toolsBefore));
    });
  });
});
